/* document-tab.c generated by valac 0.28.0, the Vala compiler
 * generated from document-tab.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <webkit2/webkit2.h>
#include <stdlib.h>
#include <string.h>
#include <gdk/gdk.h>


#define TYPE_DOCUMENT_TAB (document_tab_get_type ())
#define DOCUMENT_TAB(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DOCUMENT_TAB, DocumentTab))
#define DOCUMENT_TAB_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DOCUMENT_TAB, DocumentTabClass))
#define IS_DOCUMENT_TAB(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DOCUMENT_TAB))
#define IS_DOCUMENT_TAB_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DOCUMENT_TAB))
#define DOCUMENT_TAB_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DOCUMENT_TAB, DocumentTabClass))

typedef struct _DocumentTab DocumentTab;
typedef struct _DocumentTabClass DocumentTabClass;
typedef struct _DocumentTabPrivate DocumentTabPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))

struct _DocumentTab {
	GtkBox parent_instance;
	DocumentTabPrivate * priv;
};

struct _DocumentTabClass {
	GtkBoxClass parent_class;
};

struct _DocumentTabPrivate {
	WebKitWebView* _web_view;
	GtkEventBox* evt_box;
	GtkLabel* title_label;
	GtkEventBox* close_button;
	GtkSeparator* separator;
	gchar* filename;
	GtkScrolledWindow* _tab_widget;
	gchar* _tab_title;
};


static gpointer document_tab_parent_class = NULL;

GType document_tab_get_type (void) G_GNUC_CONST;
#define DOCUMENT_TAB_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_DOCUMENT_TAB, DocumentTabPrivate))
enum  {
	DOCUMENT_TAB_DUMMY_PROPERTY,
	DOCUMENT_TAB_WEB_VIEW,
	DOCUMENT_TAB_TAB_WIDGET,
	DOCUMENT_TAB_TAB_TITLE
};
DocumentTab* document_tab_new (const gchar* base_name, const gchar* file_path);
DocumentTab* document_tab_construct (GType object_type, const gchar* base_name, const gchar* file_path);
void document_tab_set_tab_title (DocumentTab* self, const gchar* value);
static void document_tab_create_widgets (DocumentTab* self);
const gchar* document_tab_get_tab_title (DocumentTab* self);
static gboolean document_tab_button_clicked (DocumentTab* self, GdkEventButton* evt);
static gboolean _document_tab_button_clicked_gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self);
static gboolean document_tab_tab_clicked_action (DocumentTab* self, GdkEventButton* evt);
static gboolean _document_tab_tab_clicked_action_gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self);
void document_tab_load_file (DocumentTab* self);
void document_tab_refresh_title (DocumentTab* self);
void document_tab_mark_title (DocumentTab* self);
WebKitWebView* document_tab_get_web_view (DocumentTab* self);
GtkScrolledWindow* document_tab_get_tab_widget (DocumentTab* self);
static void document_tab_finalize (GObject* obj);
static void _vala_document_tab_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_document_tab_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


DocumentTab* document_tab_construct (GType object_type, const gchar* base_name, const gchar* file_path) {
	DocumentTab * self = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	g_return_val_if_fail (base_name != NULL, NULL);
	g_return_val_if_fail (file_path != NULL, NULL);
	self = (DocumentTab*) g_object_new (object_type, NULL);
	_tmp0_ = base_name;
	document_tab_set_tab_title (self, _tmp0_);
	_tmp1_ = file_path;
	_tmp2_ = g_strdup (_tmp1_);
	_g_free0 (self->priv->filename);
	self->priv->filename = _tmp2_;
	document_tab_create_widgets (self);
	return self;
}


DocumentTab* document_tab_new (const gchar* base_name, const gchar* file_path) {
	return document_tab_construct (TYPE_DOCUMENT_TAB, base_name, file_path);
}


static gboolean _document_tab_button_clicked_gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self) {
	gboolean result;
	result = document_tab_button_clicked ((DocumentTab*) self, event);
	return result;
}


static gboolean _document_tab_tab_clicked_action_gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self) {
	gboolean result;
	result = document_tab_tab_clicked_action ((DocumentTab*) self, event);
	return result;
}


static void document_tab_create_widgets (DocumentTab* self) {
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	GtkLabel* _tmp2_ = NULL;
	GtkSeparator* _tmp3_ = NULL;
	GtkImage* close_img = NULL;
	GtkImage* _tmp4_ = NULL;
	GtkEventBox* _tmp5_ = NULL;
	GtkEventBox* _tmp6_ = NULL;
	GtkEventBox* _tmp7_ = NULL;
	GtkEventBox* _tmp8_ = NULL;
	GtkEventBox* _tmp9_ = NULL;
	GtkEventBox* _tmp10_ = NULL;
	GtkLabel* _tmp11_ = NULL;
	GtkEventBox* _tmp12_ = NULL;
	GtkEventBox* _tmp13_ = NULL;
	GtkEventBox* _tmp14_ = NULL;
	GtkEventBox* _tmp15_ = NULL;
	GtkSeparator* _tmp16_ = NULL;
	WebKitWebView* _tmp17_ = NULL;
	WebKitWebView* _tmp18_ = NULL;
	GtkScrolledWindow* _tmp19_ = NULL;
	GtkScrolledWindow* _tmp20_ = NULL;
	GtkScrolledWindow* _tmp21_ = NULL;
	WebKitWebView* _tmp22_ = NULL;
	GtkScrolledWindow* _tmp23_ = NULL;
	g_return_if_fail (self != NULL);
	gtk_orientable_set_orientation ((GtkOrientable*) self, GTK_ORIENTATION_HORIZONTAL);
	gtk_box_set_spacing ((GtkBox*) self, 0);
	_tmp0_ = document_tab_get_tab_title (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = (GtkLabel*) gtk_label_new (_tmp1_);
	g_object_ref_sink (_tmp2_);
	_g_object_unref0 (self->priv->title_label);
	self->priv->title_label = _tmp2_;
	_tmp3_ = (GtkSeparator*) gtk_separator_new (GTK_ORIENTATION_VERTICAL);
	g_object_ref_sink (_tmp3_);
	_g_object_unref0 (self->priv->separator);
	self->priv->separator = _tmp3_;
	_tmp4_ = (GtkImage*) gtk_image_new_from_icon_name ("window-close-symbolic", GTK_ICON_SIZE_MENU);
	g_object_ref_sink (_tmp4_);
	close_img = _tmp4_;
	_tmp5_ = (GtkEventBox*) gtk_event_box_new ();
	g_object_ref_sink (_tmp5_);
	_g_object_unref0 (self->priv->close_button);
	self->priv->close_button = _tmp5_;
	_tmp6_ = self->priv->close_button;
	g_object_set ((GtkContainer*) _tmp6_, "child", (GtkWidget*) close_img, NULL);
	_tmp7_ = self->priv->close_button;
	gtk_event_box_set_above_child (_tmp7_, TRUE);
	_tmp8_ = self->priv->close_button;
	g_signal_connect_object ((GtkWidget*) _tmp8_, "button-press-event", (GCallback) _document_tab_button_clicked_gtk_widget_button_press_event, self, 0);
	_tmp9_ = (GtkEventBox*) gtk_event_box_new ();
	g_object_ref_sink (_tmp9_);
	_g_object_unref0 (self->priv->evt_box);
	self->priv->evt_box = _tmp9_;
	_tmp10_ = self->priv->evt_box;
	_tmp11_ = self->priv->title_label;
	g_object_set ((GtkContainer*) _tmp10_, "child", (GtkWidget*) _tmp11_, NULL);
	_tmp12_ = self->priv->evt_box;
	gtk_event_box_set_above_child (_tmp12_, TRUE);
	_tmp13_ = self->priv->evt_box;
	g_signal_connect_object ((GtkWidget*) _tmp13_, "button-press-event", (GCallback) _document_tab_tab_clicked_action_gtk_widget_button_press_event, self, 0);
	_tmp14_ = self->priv->evt_box;
	gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) _tmp14_, TRUE, TRUE, (guint) 0);
	_tmp15_ = self->priv->close_button;
	gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) _tmp15_, FALSE, TRUE, (guint) 5);
	_tmp16_ = self->priv->separator;
	gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) _tmp16_, FALSE, TRUE, (guint) 0);
	_tmp17_ = (WebKitWebView*) webkit_web_view_new ();
	g_object_ref_sink (_tmp17_);
	_g_object_unref0 (self->priv->_web_view);
	self->priv->_web_view = _tmp17_;
	_tmp18_ = self->priv->_web_view;
	gtk_widget_show ((GtkWidget*) _tmp18_);
	_tmp19_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
	g_object_ref_sink (_tmp19_);
	_g_object_unref0 (self->priv->_tab_widget);
	self->priv->_tab_widget = _tmp19_;
	_tmp20_ = self->priv->_tab_widget;
	gtk_scrolled_window_set_policy (_tmp20_, GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
	_tmp21_ = self->priv->_tab_widget;
	_tmp22_ = self->priv->_web_view;
	gtk_container_add ((GtkContainer*) _tmp21_, (GtkWidget*) _tmp22_);
	_tmp23_ = self->priv->_tab_widget;
	gtk_widget_show ((GtkWidget*) _tmp23_);
	document_tab_load_file (self);
	gtk_widget_show_all ((GtkWidget*) self);
	_g_object_unref0 (close_img);
}


static gboolean string_contains (const gchar* self, const gchar* needle) {
	gboolean result = FALSE;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (needle != NULL, FALSE);
	_tmp0_ = needle;
	_tmp1_ = strstr ((gchar*) self, (gchar*) _tmp0_);
	result = _tmp1_ != NULL;
	return result;
}


void document_tab_load_file (DocumentTab* self) {
	const gchar* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gchar* timestamp = NULL;
	GDateTime* _tmp6_ = NULL;
	GDateTime* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	gchar* prefix = NULL;
	const gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gchar* html_filename = NULL;
	const gchar* _tmp12_ = NULL;
	const gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	gchar* html_header = NULL;
	gchar* _tmp15_ = NULL;
	const gchar* _tmp16_ = NULL;
	gchar* _tmp17_ = NULL;
	const gchar* _tmp18_ = NULL;
	gchar* _tmp19_ = NULL;
	const gchar* _tmp20_ = NULL;
	gchar* _tmp21_ = NULL;
	const gchar* _tmp22_ = NULL;
	gchar* _tmp23_ = NULL;
	gchar* _tmp24_ = NULL;
	gchar* _tmp25_ = NULL;
	gchar* _tmp26_ = NULL;
	const gchar* _tmp27_ = NULL;
	gchar* _tmp28_ = NULL;
	gchar* _tmp29_ = NULL;
	const gchar* _tmp30_ = NULL;
	gchar* _tmp31_ = NULL;
	gchar* _tmp32_ = NULL;
	gchar* _tmp33_ = NULL;
	gchar* _tmp34_ = NULL;
	const gchar* _tmp35_ = NULL;
	gchar* _tmp36_ = NULL;
	gchar* _tmp37_ = NULL;
	const gchar* _tmp38_ = NULL;
	gchar* _tmp39_ = NULL;
	gchar* _tmp40_ = NULL;
	WebKitWebView* _tmp41_ = NULL;
	const gchar* _tmp42_ = NULL;
	gchar* _tmp43_ = NULL;
	gchar* _tmp44_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->filename;
	_tmp1_ = string_contains (_tmp0_, ".html");
	if (_tmp1_) {
		WebKitWebView* _tmp2_ = NULL;
		const gchar* _tmp3_ = NULL;
		gchar* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		_tmp2_ = self->priv->_web_view;
		_tmp3_ = self->priv->filename;
		_tmp4_ = g_strconcat ("file://", _tmp3_, NULL);
		_tmp5_ = _tmp4_;
		webkit_web_view_load_uri (_tmp2_, _tmp5_);
		_g_free0 (_tmp5_);
		return;
	}
	_tmp6_ = g_date_time_new_now_utc ();
	_tmp7_ = _tmp6_;
	_tmp8_ = g_date_time_format (_tmp7_, "%F_%T");
	_tmp9_ = _tmp8_;
	_g_date_time_unref0 (_tmp7_);
	timestamp = _tmp9_;
	_tmp10_ = g_get_home_dir ();
	_tmp11_ = g_strconcat (_tmp10_, "/.markdown-reader/tmp", NULL);
	prefix = _tmp11_;
	_tmp12_ = prefix;
	_tmp13_ = timestamp;
	_tmp14_ = g_strdup_printf ("%s/tmp-%s.html", _tmp12_, _tmp13_);
	html_filename = _tmp14_;
	_tmp15_ = g_strdup ("<!DOCTYPE html><html><head>");
	html_header = _tmp15_;
	_tmp16_ = html_header;
	_tmp17_ = g_strconcat (_tmp16_, "<meta http-equiv=\"Content-Type\"", NULL);
	_g_free0 (html_header);
	html_header = _tmp17_;
	_tmp18_ = html_header;
	_tmp19_ = g_strconcat (_tmp18_, "content=\"text/html; charset=UTF-8\">", NULL);
	_g_free0 (html_header);
	html_header = _tmp19_;
	_tmp20_ = html_header;
	_tmp21_ = g_strconcat (_tmp20_, "</head><body>", NULL);
	_g_free0 (html_header);
	html_header = _tmp21_;
	_tmp22_ = html_header;
	_tmp23_ = g_strconcat ("echo '", _tmp22_, NULL);
	_tmp24_ = _tmp23_;
	_tmp25_ = g_strconcat (_tmp24_, "' > ", NULL);
	_tmp26_ = _tmp25_;
	_tmp27_ = html_filename;
	_tmp28_ = g_strconcat (_tmp26_, _tmp27_, NULL);
	_tmp29_ = _tmp28_;
	system (_tmp29_);
	_g_free0 (_tmp29_);
	_g_free0 (_tmp26_);
	_g_free0 (_tmp24_);
	_tmp30_ = self->priv->filename;
	_tmp31_ = g_strconcat ("markdown_py \"", _tmp30_, NULL);
	_tmp32_ = _tmp31_;
	_tmp33_ = g_strconcat (_tmp32_, "\" >> ", NULL);
	_tmp34_ = _tmp33_;
	_tmp35_ = html_filename;
	_tmp36_ = g_strconcat (_tmp34_, _tmp35_, NULL);
	_tmp37_ = _tmp36_;
	system (_tmp37_);
	_g_free0 (_tmp37_);
	_g_free0 (_tmp34_);
	_g_free0 (_tmp32_);
	_tmp38_ = html_filename;
	_tmp39_ = g_strconcat ("echo '</body></html>' >> ", _tmp38_, NULL);
	_tmp40_ = _tmp39_;
	system (_tmp40_);
	_g_free0 (_tmp40_);
	_tmp41_ = self->priv->_web_view;
	_tmp42_ = html_filename;
	_tmp43_ = g_strconcat ("file://", _tmp42_, NULL);
	_tmp44_ = _tmp43_;
	webkit_web_view_load_uri (_tmp41_, _tmp44_);
	_g_free0 (_tmp44_);
	_g_free0 (html_header);
	_g_free0 (html_filename);
	_g_free0 (prefix);
	_g_free0 (timestamp);
}


void document_tab_refresh_title (DocumentTab* self) {
	GtkLabel* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->title_label;
	if (_tmp0_ != NULL) {
		GtkLabel* _tmp1_ = NULL;
		GtkLabel* _tmp2_ = NULL;
		const gchar* _tmp3_ = NULL;
		const gchar* _tmp4_ = NULL;
		_tmp1_ = self->priv->title_label;
		gtk_label_set_use_markup (_tmp1_, FALSE);
		_tmp2_ = self->priv->title_label;
		_tmp3_ = document_tab_get_tab_title (self);
		_tmp4_ = _tmp3_;
		gtk_label_set_label (_tmp2_, _tmp4_);
	}
}


static gboolean document_tab_button_clicked (DocumentTab* self, GdkEventButton* evt) {
	gboolean result = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (evt != NULL, FALSE);
	g_signal_emit_by_name (self, "close-clicked", self);
	result = TRUE;
	return result;
}


static gboolean document_tab_tab_clicked_action (DocumentTab* self, GdkEventButton* evt) {
	gboolean result = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (evt != NULL, FALSE);
	g_signal_emit_by_name (self, "tab-clicked", self);
	document_tab_mark_title (self);
	result = TRUE;
	return result;
}


void document_tab_mark_title (DocumentTab* self) {
	GtkLabel* _tmp0_ = NULL;
	GtkLabel* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->title_label;
	gtk_label_set_use_markup (_tmp0_, TRUE);
	_tmp1_ = self->priv->title_label;
	_tmp2_ = document_tab_get_tab_title (self);
	_tmp3_ = _tmp2_;
	_tmp4_ = g_strconcat ("<b>", _tmp3_, NULL);
	_tmp5_ = _tmp4_;
	_tmp6_ = g_strconcat (_tmp5_, "</b>", NULL);
	_tmp7_ = _tmp6_;
	gtk_label_set_label (_tmp1_, _tmp7_);
	_g_free0 (_tmp7_);
	_g_free0 (_tmp5_);
}


WebKitWebView* document_tab_get_web_view (DocumentTab* self) {
	WebKitWebView* result;
	WebKitWebView* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_web_view;
	result = _tmp0_;
	return result;
}


GtkScrolledWindow* document_tab_get_tab_widget (DocumentTab* self) {
	GtkScrolledWindow* result;
	GtkScrolledWindow* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_tab_widget;
	result = _tmp0_;
	return result;
}


const gchar* document_tab_get_tab_title (DocumentTab* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_tab_title;
	result = _tmp0_;
	return result;
}


void document_tab_set_tab_title (DocumentTab* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_tab_title;
	_tmp1_ = value;
	if (g_strcmp0 (_tmp0_, _tmp1_) == 0) {
		return;
	}
	_tmp2_ = value;
	_tmp3_ = g_strdup (_tmp2_);
	_g_free0 (self->priv->_tab_title);
	self->priv->_tab_title = _tmp3_;
	document_tab_refresh_title (self);
	g_object_notify ((GObject *) self, "tab-title");
}


static void document_tab_class_init (DocumentTabClass * klass) {
	document_tab_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (DocumentTabPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_document_tab_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_document_tab_set_property;
	G_OBJECT_CLASS (klass)->finalize = document_tab_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), DOCUMENT_TAB_WEB_VIEW, g_param_spec_object ("web-view", "web-view", "web-view", webkit_web_view_get_type (), G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), DOCUMENT_TAB_TAB_WIDGET, g_param_spec_object ("tab-widget", "tab-widget", "tab-widget", gtk_scrolled_window_get_type (), G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), DOCUMENT_TAB_TAB_TITLE, g_param_spec_string ("tab-title", "tab-title", "tab-title", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_signal_new ("close_clicked", TYPE_DOCUMENT_TAB, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__OBJECT, G_TYPE_NONE, 1, TYPE_DOCUMENT_TAB);
	g_signal_new ("tab_clicked", TYPE_DOCUMENT_TAB, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__OBJECT, G_TYPE_NONE, 1, TYPE_DOCUMENT_TAB);
	g_signal_new ("tab_focused", TYPE_DOCUMENT_TAB, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__OBJECT, G_TYPE_NONE, 1, TYPE_DOCUMENT_TAB);
}


static void document_tab_instance_init (DocumentTab * self) {
	self->priv = DOCUMENT_TAB_GET_PRIVATE (self);
}


static void document_tab_finalize (GObject* obj) {
	DocumentTab * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_DOCUMENT_TAB, DocumentTab);
	_g_object_unref0 (self->priv->_web_view);
	_g_object_unref0 (self->priv->evt_box);
	_g_object_unref0 (self->priv->title_label);
	_g_object_unref0 (self->priv->close_button);
	_g_object_unref0 (self->priv->separator);
	_g_free0 (self->priv->filename);
	_g_object_unref0 (self->priv->_tab_widget);
	_g_free0 (self->priv->_tab_title);
	G_OBJECT_CLASS (document_tab_parent_class)->finalize (obj);
}


GType document_tab_get_type (void) {
	static volatile gsize document_tab_type_id__volatile = 0;
	if (g_once_init_enter (&document_tab_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (DocumentTabClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) document_tab_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DocumentTab), 0, (GInstanceInitFunc) document_tab_instance_init, NULL };
		GType document_tab_type_id;
		document_tab_type_id = g_type_register_static (gtk_box_get_type (), "DocumentTab", &g_define_type_info, 0);
		g_once_init_leave (&document_tab_type_id__volatile, document_tab_type_id);
	}
	return document_tab_type_id__volatile;
}


static void _vala_document_tab_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	DocumentTab * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_DOCUMENT_TAB, DocumentTab);
	switch (property_id) {
		case DOCUMENT_TAB_WEB_VIEW:
		g_value_set_object (value, document_tab_get_web_view (self));
		break;
		case DOCUMENT_TAB_TAB_WIDGET:
		g_value_set_object (value, document_tab_get_tab_widget (self));
		break;
		case DOCUMENT_TAB_TAB_TITLE:
		g_value_set_string (value, document_tab_get_tab_title (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_document_tab_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	DocumentTab * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_DOCUMENT_TAB, DocumentTab);
	switch (property_id) {
		case DOCUMENT_TAB_TAB_TITLE:
		document_tab_set_tab_title (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



