/* main-window.c generated by valac 0.28.0, the Vala compiler
 * generated from main-window.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <gdk/gdk.h>


#define TYPE_MAIN_WINDOW (main_window_get_type ())
#define MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAIN_WINDOW, MainWindow))
#define MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MAIN_WINDOW, MainWindowClass))
#define IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAIN_WINDOW))
#define IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MAIN_WINDOW))
#define MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MAIN_WINDOW, MainWindowClass))

typedef struct _MainWindow MainWindow;
typedef struct _MainWindowClass MainWindowClass;
typedef struct _MainWindowPrivate MainWindowPrivate;

#define TYPE_TAB_BAR (tab_bar_get_type ())
#define TAB_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TAB_BAR, TabBar))
#define TAB_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TAB_BAR, TabBarClass))
#define IS_TAB_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TAB_BAR))
#define IS_TAB_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TAB_BAR))
#define TAB_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TAB_BAR, TabBarClass))

typedef struct _TabBar TabBar;
typedef struct _TabBarClass TabBarClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define __g_list_free__g_free0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_free0_ (var), NULL)))

#define TYPE_DOCUMENT_TAB (document_tab_get_type ())
#define DOCUMENT_TAB(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DOCUMENT_TAB, DocumentTab))
#define DOCUMENT_TAB_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DOCUMENT_TAB, DocumentTabClass))
#define IS_DOCUMENT_TAB(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DOCUMENT_TAB))
#define IS_DOCUMENT_TAB_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DOCUMENT_TAB))
#define DOCUMENT_TAB_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DOCUMENT_TAB, DocumentTabClass))

typedef struct _DocumentTab DocumentTab;
typedef struct _DocumentTabClass DocumentTabClass;
#define __g_slist_free__g_free0_0(var) ((var == NULL) ? NULL : (var = (_g_slist_free__g_free0_ (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _TabBarPrivate TabBarPrivate;

struct _MainWindow {
	GtkApplicationWindow parent_instance;
	MainWindowPrivate * priv;
};

struct _MainWindowClass {
	GtkApplicationWindowClass parent_class;
};

struct _MainWindowPrivate {
	GtkHeaderBar* headerbar;
	TabBar* tab_bar;
	GtkStack* documents;
	GtkSeparator* separator;
	GList* opened_files;
	gint counter;
	GFile** _arg_files;
	gint _arg_files_length1;
	gint __arg_files_size_;
};

struct _TabBar {
	GtkBox parent_instance;
	TabBarPrivate * priv;
	gint tab_num;
};

struct _TabBarClass {
	GtkBoxClass parent_class;
};


static gpointer main_window_parent_class = NULL;

GType main_window_get_type (void) G_GNUC_CONST;
GType tab_bar_get_type (void) G_GNUC_CONST;
#define MAIN_WINDOW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_MAIN_WINDOW, MainWindowPrivate))
enum  {
	MAIN_WINDOW_DUMMY_PROPERTY
};
static void _g_free0_ (gpointer var);
static void _g_list_free__g_free0_ (GList* self);
MainWindow* main_window_new (GtkApplication* app);
MainWindow* main_window_construct (GType object_type, GtkApplication* app);
static void main_window_create_widgets (MainWindow* self);
static void main_window_prev_tab_cb (MainWindow* self);
static void _main_window_prev_tab_cb_gtk_button_clicked (GtkButton* _sender, gpointer self);
static void main_window_next_tab_cb (MainWindow* self);
static void _main_window_next_tab_cb_gtk_button_clicked (GtkButton* _sender, gpointer self);
static void main_window_open_file_cb (MainWindow* self);
static void _main_window_open_file_cb_gtk_button_clicked (GtkButton* _sender, gpointer self);
static void main_window_page_refresh_cb (MainWindow* self);
static void _main_window_page_refresh_cb_gtk_button_clicked (GtkButton* _sender, gpointer self);
TabBar* tab_bar_new (void);
TabBar* tab_bar_construct (GType object_type);
void tab_bar_set_stack (TabBar* self, GtkStack* stack);
GType document_tab_get_type (void) G_GNUC_CONST;
static void main_window_on_page_close (MainWindow* self, DocumentTab* tab, gint page_num);
static void _main_window_on_page_close_tab_bar_page_closed (TabBar* _sender, DocumentTab* tab, gint page_num, gpointer self);
static void main_window_welcome_msg (MainWindow* self);
static void ___lambda7_ (MainWindow* self, const gchar* entry);
static void main_window_add_new_tab_from_file (MainWindow* self, const gchar* file_name);
static void ____lambda7__gfunc (gconstpointer data, gpointer self);
static void _g_slist_free__g_free0_ (GSList* self);
static gboolean main_window_file_is_opened (MainWindow* self, const gchar* needle);
DocumentTab* document_tab_new (const gchar* base_name, const gchar* file_path);
DocumentTab* document_tab_construct (GType object_type, const gchar* base_name, const gchar* file_path);
GtkScrolledWindow* document_tab_get_tab_widget (DocumentTab* self);
void tab_bar_add_page (TabBar* self, DocumentTab* tab, gboolean new_page);
DocumentTab* tab_bar_get_current_page (TabBar* self, GtkWidget* current_doc);
gint tab_bar_get_page_num (TabBar* self, DocumentTab* tab);
void tab_bar_switch_page_next (TabBar* self, DocumentTab* current_tab);
void document_tab_mark_title (DocumentTab* self);
void document_tab_load_file (DocumentTab* self);
void tab_bar_switch_page_prev (TabBar* self, DocumentTab* current_tab);
void main_window_set_arg_files (MainWindow* self, GFile** value, int value_length1);
static GFile** _vala_array_dup1 (GFile** self, int length);
static void main_window_finalize (GObject* obj);
static void _vala_main_window_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static void _g_free0_ (gpointer var) {
	var = (g_free (var), NULL);
}


static void _g_list_free__g_free0_ (GList* self) {
	g_list_foreach (self, (GFunc) _g_free0_, NULL);
	g_list_free (self);
}


MainWindow* main_window_construct (GType object_type, GtkApplication* app) {
	MainWindow * self = NULL;
	GtkApplication* _tmp0_ = NULL;
	g_return_val_if_fail (app != NULL, NULL);
	_tmp0_ = app;
	self = (MainWindow*) g_object_new (object_type, "application", _tmp0_, NULL);
	__g_list_free__g_free0_0 (self->priv->opened_files);
	self->priv->opened_files = NULL;
	g_object_set ((GtkWindow*) self, "window-position", GTK_WIN_POS_CENTER_ALWAYS, NULL);
	gtk_window_set_default_size ((GtkWindow*) self, 700, 600);
	gtk_container_set_border_width ((GtkContainer*) self, (guint) 0);
	main_window_create_widgets (self);
	return self;
}


MainWindow* main_window_new (GtkApplication* app) {
	return main_window_construct (TYPE_MAIN_WINDOW, app);
}


static void _main_window_prev_tab_cb_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	main_window_prev_tab_cb ((MainWindow*) self);
}


static void _main_window_next_tab_cb_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	main_window_next_tab_cb ((MainWindow*) self);
}


static void _main_window_open_file_cb_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	main_window_open_file_cb ((MainWindow*) self);
}


static void _main_window_page_refresh_cb_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	main_window_page_refresh_cb ((MainWindow*) self);
}


static void _main_window_on_page_close_tab_bar_page_closed (TabBar* _sender, DocumentTab* tab, gint page_num, gpointer self) {
	main_window_on_page_close ((MainWindow*) self, tab, page_num);
}


static void main_window_create_widgets (MainWindow* self) {
	GtkHeaderBar* _tmp0_ = NULL;
	GtkHeaderBar* _tmp1_ = NULL;
	GtkHeaderBar* _tmp2_ = NULL;
	GtkHeaderBar* _tmp3_ = NULL;
	GtkHeaderBar* _tmp4_ = NULL;
	GtkButton* prev_tab_button = NULL;
	GtkButton* _tmp5_ = NULL;
	GtkButton* next_tab_button = NULL;
	GtkButton* _tmp6_ = NULL;
	GtkButton* open_button = NULL;
	GtkButton* _tmp7_ = NULL;
	GtkButton* refresh_button = NULL;
	GtkButton* _tmp8_ = NULL;
	GtkAccelGroup* accels = NULL;
	GtkAccelGroup* _tmp9_ = NULL;
	GtkHeaderBar* _tmp10_ = NULL;
	GtkHeaderBar* _tmp11_ = NULL;
	GtkHeaderBar* _tmp12_ = NULL;
	GtkHeaderBar* _tmp13_ = NULL;
	GtkStack* _tmp14_ = NULL;
	GtkStack* _tmp15_ = NULL;
	GtkStack* _tmp16_ = NULL;
	GtkStack* _tmp17_ = NULL;
	TabBar* _tmp18_ = NULL;
	TabBar* _tmp19_ = NULL;
	GtkStack* _tmp20_ = NULL;
	TabBar* _tmp21_ = NULL;
	GtkSeparator* _tmp22_ = NULL;
	GtkBox* content = NULL;
	GtkBox* _tmp23_ = NULL;
	TabBar* _tmp24_ = NULL;
	GtkSeparator* _tmp25_ = NULL;
	GtkStack* _tmp26_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = (GtkHeaderBar*) gtk_header_bar_new ();
	g_object_ref_sink (_tmp0_);
	_g_object_unref0 (self->priv->headerbar);
	self->priv->headerbar = _tmp0_;
	_tmp1_ = self->priv->headerbar;
	gtk_header_bar_set_show_close_button (_tmp1_, TRUE);
	_tmp2_ = self->priv->headerbar;
	gtk_window_set_titlebar ((GtkWindow*) self, (GtkWidget*) _tmp2_);
	_tmp3_ = self->priv->headerbar;
	gtk_header_bar_set_title (_tmp3_, "Markdown Reader");
	_tmp4_ = self->priv->headerbar;
	gtk_widget_show ((GtkWidget*) _tmp4_);
	_tmp5_ = (GtkButton*) gtk_button_new_from_icon_name ("go-previous-symbolic", GTK_ICON_SIZE_MENU);
	g_object_ref_sink (_tmp5_);
	prev_tab_button = _tmp5_;
	gtk_widget_set_tooltip_text ((GtkWidget*) prev_tab_button, "Previous tab" " (Ctrl+PageUp)");
	gtk_widget_show ((GtkWidget*) prev_tab_button);
	_tmp6_ = (GtkButton*) gtk_button_new_from_icon_name ("go-next-symbolic", GTK_ICON_SIZE_MENU);
	g_object_ref_sink (_tmp6_);
	next_tab_button = _tmp6_;
	gtk_widget_set_tooltip_text ((GtkWidget*) next_tab_button, "Next tab" " (Ctrl+PageDown)");
	gtk_widget_show ((GtkWidget*) next_tab_button);
	_tmp7_ = (GtkButton*) gtk_button_new_from_icon_name ("document-open-symbolic", GTK_ICON_SIZE_MENU);
	g_object_ref_sink (_tmp7_);
	open_button = _tmp7_;
	gtk_widget_set_tooltip_text ((GtkWidget*) open_button, "Open file" " (Ctrl+O)");
	gtk_widget_show ((GtkWidget*) open_button);
	_tmp8_ = (GtkButton*) gtk_button_new_from_icon_name ("view-refresh-symbolic", GTK_ICON_SIZE_MENU);
	g_object_ref_sink (_tmp8_);
	refresh_button = _tmp8_;
	gtk_widget_set_tooltip_text ((GtkWidget*) refresh_button, "Refresh document" " (Ctrl+R)");
	gtk_widget_show ((GtkWidget*) refresh_button);
	g_signal_connect_object (prev_tab_button, "clicked", (GCallback) _main_window_prev_tab_cb_gtk_button_clicked, self, 0);
	g_signal_connect_object (next_tab_button, "clicked", (GCallback) _main_window_next_tab_cb_gtk_button_clicked, self, 0);
	g_signal_connect_object (open_button, "clicked", (GCallback) _main_window_open_file_cb_gtk_button_clicked, self, 0);
	g_signal_connect_object (refresh_button, "clicked", (GCallback) _main_window_page_refresh_cb_gtk_button_clicked, self, 0);
	_tmp9_ = gtk_accel_group_new ();
	accels = _tmp9_;
	gtk_window_add_accel_group ((GtkWindow*) self, accels);
	gtk_widget_add_accelerator ((GtkWidget*) open_button, "activate", accels, (guint) GDK_KEY_O, GDK_CONTROL_MASK, GTK_ACCEL_VISIBLE);
	gtk_widget_add_accelerator ((GtkWidget*) prev_tab_button, "activate", accels, (guint) GDK_KEY_Page_Up, GDK_CONTROL_MASK, GTK_ACCEL_VISIBLE);
	gtk_widget_add_accelerator ((GtkWidget*) next_tab_button, "activate", accels, (guint) GDK_KEY_Page_Down, GDK_CONTROL_MASK, GTK_ACCEL_VISIBLE);
	gtk_widget_add_accelerator ((GtkWidget*) refresh_button, "activate", accels, (guint) GDK_KEY_R, GDK_CONTROL_MASK, GTK_ACCEL_VISIBLE);
	_tmp10_ = self->priv->headerbar;
	gtk_header_bar_pack_start (_tmp10_, (GtkWidget*) prev_tab_button);
	_tmp11_ = self->priv->headerbar;
	gtk_header_bar_pack_start (_tmp11_, (GtkWidget*) next_tab_button);
	_tmp12_ = self->priv->headerbar;
	gtk_header_bar_pack_start (_tmp12_, (GtkWidget*) open_button);
	_tmp13_ = self->priv->headerbar;
	gtk_header_bar_pack_end (_tmp13_, (GtkWidget*) refresh_button);
	_tmp14_ = (GtkStack*) gtk_stack_new ();
	g_object_ref_sink (_tmp14_);
	_g_object_unref0 (self->priv->documents);
	self->priv->documents = _tmp14_;
	_tmp15_ = self->priv->documents;
	gtk_stack_set_transition_type (_tmp15_, GTK_STACK_TRANSITION_TYPE_OVER_LEFT_RIGHT);
	_tmp16_ = self->priv->documents;
	gtk_stack_set_transition_duration (_tmp16_, (guint) 250);
	_tmp17_ = self->priv->documents;
	gtk_widget_show ((GtkWidget*) _tmp17_);
	_tmp18_ = tab_bar_new ();
	g_object_ref_sink (_tmp18_);
	_g_object_unref0 (self->priv->tab_bar);
	self->priv->tab_bar = _tmp18_;
	_tmp19_ = self->priv->tab_bar;
	_tmp20_ = self->priv->documents;
	tab_bar_set_stack (_tmp19_, _tmp20_);
	_tmp21_ = self->priv->tab_bar;
	g_signal_connect_object (_tmp21_, "page-closed", (GCallback) _main_window_on_page_close_tab_bar_page_closed, self, 0);
	_tmp22_ = (GtkSeparator*) gtk_separator_new (GTK_ORIENTATION_HORIZONTAL);
	g_object_ref_sink (_tmp22_);
	_g_object_unref0 (self->priv->separator);
	self->priv->separator = _tmp22_;
	_tmp23_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
	g_object_ref_sink (_tmp23_);
	content = _tmp23_;
	_tmp24_ = self->priv->tab_bar;
	gtk_box_pack_start (content, (GtkWidget*) _tmp24_, FALSE, TRUE, (guint) 7);
	_tmp25_ = self->priv->separator;
	gtk_box_pack_start (content, (GtkWidget*) _tmp25_, FALSE, TRUE, (guint) 0);
	_tmp26_ = self->priv->documents;
	gtk_box_pack_start (content, (GtkWidget*) _tmp26_, TRUE, TRUE, (guint) 0);
	gtk_widget_show ((GtkWidget*) content);
	main_window_welcome_msg (self);
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) content);
	_g_object_unref0 (content);
	_g_object_unref0 (accels);
	_g_object_unref0 (refresh_button);
	_g_object_unref0 (open_button);
	_g_object_unref0 (next_tab_button);
	_g_object_unref0 (prev_tab_button);
}


static void main_window_welcome_msg (MainWindow* self) {
	GtkLabel* l1 = NULL;
	GtkLabel* _tmp0_ = NULL;
	GtkLabel* l2 = NULL;
	GtkLabel* _tmp1_ = NULL;
	GtkLabel* l3 = NULL;
	GtkLabel* _tmp2_ = NULL;
	GtkLabel* l4 = NULL;
	GtkLabel* _tmp3_ = NULL;
	GtkLabel* l5 = NULL;
	GtkLabel* _tmp4_ = NULL;
	GtkImage* open = NULL;
	GtkImage* _tmp5_ = NULL;
	GtkBox* hbox = NULL;
	GtkBox* _tmp6_ = NULL;
	GtkBox* box = NULL;
	GtkBox* _tmp7_ = NULL;
	GtkStack* _tmp8_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = (GtkLabel*) gtk_label_new ("<big><b>" "Welcome!" "</b></big>");
	g_object_ref_sink (_tmp0_);
	l1 = _tmp0_;
	_tmp1_ = (GtkLabel*) gtk_label_new ("Markdown Reader allows you to easily read");
	g_object_ref_sink (_tmp1_);
	l2 = _tmp1_;
	_tmp2_ = (GtkLabel*) gtk_label_new ("the content of your markdown and html files.");
	g_object_ref_sink (_tmp2_);
	l3 = _tmp2_;
	gtk_label_set_use_markup (l1, TRUE);
	_tmp3_ = (GtkLabel*) gtk_label_new ("Click the");
	g_object_ref_sink (_tmp3_);
	l4 = _tmp3_;
	_tmp4_ = (GtkLabel*) gtk_label_new ("button to open a file...");
	g_object_ref_sink (_tmp4_);
	l5 = _tmp4_;
	_tmp5_ = (GtkImage*) gtk_image_new_from_icon_name ("document-open-symbolic", GTK_ICON_SIZE_MENU);
	g_object_ref_sink (_tmp5_);
	open = _tmp5_;
	_tmp6_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 0);
	g_object_ref_sink (_tmp6_);
	hbox = _tmp6_;
	gtk_box_pack_start (hbox, (GtkWidget*) l4, FALSE, FALSE, (guint) 0);
	gtk_box_pack_start (hbox, (GtkWidget*) open, FALSE, FALSE, (guint) 5);
	gtk_box_pack_start (hbox, (GtkWidget*) l5, FALSE, FALSE, (guint) 0);
	gtk_widget_set_halign ((GtkWidget*) hbox, GTK_ALIGN_CENTER);
	_tmp7_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
	g_object_ref_sink (_tmp7_);
	box = _tmp7_;
	gtk_box_pack_start (box, (GtkWidget*) l1, FALSE, TRUE, (guint) 10);
	gtk_box_pack_start (box, (GtkWidget*) l2, FALSE, TRUE, (guint) 0);
	gtk_box_pack_start (box, (GtkWidget*) l3, FALSE, TRUE, (guint) 0);
	gtk_box_pack_start (box, (GtkWidget*) hbox, FALSE, TRUE, (guint) 15);
	gtk_widget_show_all ((GtkWidget*) box);
	_tmp8_ = self->priv->documents;
	gtk_stack_add_named (_tmp8_, (GtkWidget*) box, "welcome");
	_g_object_unref0 (box);
	_g_object_unref0 (hbox);
	_g_object_unref0 (open);
	_g_object_unref0 (l5);
	_g_object_unref0 (l4);
	_g_object_unref0 (l3);
	_g_object_unref0 (l2);
	_g_object_unref0 (l1);
}


static void ___lambda7_ (MainWindow* self, const gchar* entry) {
	const gchar* _tmp0_ = NULL;
	g_return_if_fail (entry != NULL);
	_tmp0_ = entry;
	main_window_add_new_tab_from_file (self, (const gchar*) _tmp0_);
}


static void ____lambda7__gfunc (gconstpointer data, gpointer self) {
	___lambda7_ ((MainWindow*) self, (const gchar*) data);
}


static void _g_slist_free__g_free0_ (GSList* self) {
	g_slist_foreach (self, (GFunc) _g_free0_, NULL);
	g_slist_free (self);
}


static void main_window_open_file_cb (MainWindow* self) {
	GtkFileChooserDialog* file_chooser = NULL;
	GtkFileChooserDialog* _tmp0_ = NULL;
	GtkFileChooserDialog* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	GtkFileChooserDialog* _tmp3_ = NULL;
	GtkFileChooserDialog* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	GtkFileChooserDialog* _tmp10_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = (GtkFileChooserDialog*) gtk_file_chooser_dialog_new ("Open File", (GtkWindow*) self, GTK_FILE_CHOOSER_ACTION_OPEN, "Cancel", GTK_RESPONSE_CANCEL, "Open", GTK_RESPONSE_ACCEPT, NULL);
	g_object_ref_sink (_tmp0_);
	file_chooser = _tmp0_;
	_tmp1_ = file_chooser;
	_tmp2_ = g_get_home_dir ();
	gtk_file_chooser_set_current_folder ((GtkFileChooser*) _tmp1_, _tmp2_);
	_tmp3_ = file_chooser;
	gtk_file_chooser_set_select_multiple ((GtkFileChooser*) _tmp3_, TRUE);
	_tmp4_ = file_chooser;
	_tmp5_ = gtk_dialog_run ((GtkDialog*) _tmp4_);
	if (_tmp5_ == ((gint) GTK_RESPONSE_ACCEPT)) {
		GSList* file_names = NULL;
		GtkFileChooserDialog* _tmp6_ = NULL;
		GSList* _tmp7_ = NULL;
		GtkFileChooserDialog* _tmp8_ = NULL;
		GSList* _tmp9_ = NULL;
		_tmp6_ = file_chooser;
		_tmp7_ = gtk_file_chooser_get_filenames ((GtkFileChooser*) _tmp6_);
		file_names = _tmp7_;
		_tmp8_ = file_chooser;
		gtk_widget_destroy ((GtkWidget*) _tmp8_);
		_tmp9_ = file_names;
		g_slist_foreach (_tmp9_, ____lambda7__gfunc, self);
		__g_slist_free__g_free0_0 (file_names);
	}
	_tmp10_ = file_chooser;
	if (_tmp10_ != NULL) {
		GtkFileChooserDialog* _tmp11_ = NULL;
		_tmp11_ = file_chooser;
		gtk_widget_destroy ((GtkWidget*) _tmp11_);
	}
	_g_object_unref0 (file_chooser);
}


static gboolean string_contains (const gchar* self, const gchar* needle) {
	gboolean result = FALSE;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (needle != NULL, FALSE);
	_tmp0_ = needle;
	_tmp1_ = strstr ((gchar*) self, (gchar*) _tmp0_);
	result = _tmp1_ != NULL;
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void main_window_add_new_tab_from_file (MainWindow* self, const gchar* file_name) {
	const gchar* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	const gchar* _tmp3_ = NULL;
	gboolean _tmp4_ = FALSE;
	TabBar* _tmp18_ = NULL;
	GtkSeparator* _tmp19_ = NULL;
	gchar* tab_title = NULL;
	gint _tmp20_ = 0;
	gchar* _tmp21_ = NULL;
	DocumentTab* tab = NULL;
	const gchar* _tmp22_ = NULL;
	gchar* _tmp23_ = NULL;
	gchar* _tmp24_ = NULL;
	const gchar* _tmp25_ = NULL;
	DocumentTab* _tmp26_ = NULL;
	DocumentTab* _tmp27_ = NULL;
	GtkStack* _tmp28_ = NULL;
	DocumentTab* _tmp29_ = NULL;
	GtkScrolledWindow* _tmp30_ = NULL;
	GtkScrolledWindow* _tmp31_ = NULL;
	const gchar* _tmp32_ = NULL;
	TabBar* _tmp33_ = NULL;
	DocumentTab* _tmp34_ = NULL;
	DocumentTab* current_page = NULL;
	TabBar* _tmp35_ = NULL;
	GtkStack* _tmp36_ = NULL;
	GtkWidget* _tmp37_ = NULL;
	GtkWidget* _tmp38_ = NULL;
	DocumentTab* _tmp39_ = NULL;
	gint page_num = 0;
	TabBar* _tmp40_ = NULL;
	DocumentTab* _tmp41_ = NULL;
	gint _tmp42_ = 0;
	const gchar* _tmp43_ = NULL;
	gchar* _tmp44_ = NULL;
	gint _tmp45_ = 0;
	g_return_if_fail (self != NULL);
	g_return_if_fail (file_name != NULL);
	_tmp0_ = file_name;
	_tmp1_ = main_window_file_is_opened (self, _tmp0_);
	if (_tmp1_) {
		return;
	}
	_tmp3_ = file_name;
	_tmp4_ = string_contains (_tmp3_, ".html");
	if (!_tmp4_) {
		const gchar* _tmp5_ = NULL;
		gboolean _tmp6_ = FALSE;
		_tmp5_ = file_name;
		_tmp6_ = string_contains (_tmp5_, ".md");
		_tmp2_ = !_tmp6_;
	} else {
		_tmp2_ = FALSE;
	}
	if (_tmp2_) {
		GtkDialog* dialog = NULL;
		GtkDialog* _tmp7_ = NULL;
		GtkLabel* ns_filetype = NULL;
		GtkLabel* _tmp8_ = NULL;
		GtkLabel* _tmp9_ = NULL;
		GtkBox* content = NULL;
		GtkDialog* _tmp10_ = NULL;
		GtkBox* _tmp11_ = NULL;
		GtkBox* _tmp12_ = NULL;
		GtkBox* _tmp13_ = NULL;
		GtkLabel* _tmp14_ = NULL;
		GtkDialog* _tmp15_ = NULL;
		GtkDialog* _tmp16_ = NULL;
		GtkDialog* _tmp17_ = NULL;
		_tmp7_ = (GtkDialog*) gtk_dialog_new_with_buttons ("Error", (GtkWindow*) self, GTK_DIALOG_MODAL, "Accept", GTK_RESPONSE_ACCEPT, NULL, NULL);
		g_object_ref_sink (_tmp7_);
		dialog = _tmp7_;
		_tmp8_ = (GtkLabel*) gtk_label_new ("This file type is not supported!");
		g_object_ref_sink (_tmp8_);
		ns_filetype = _tmp8_;
		_tmp9_ = ns_filetype;
		gtk_widget_show ((GtkWidget*) _tmp9_);
		_tmp10_ = dialog;
		_tmp11_ = (GtkBox*) gtk_dialog_get_content_area (_tmp10_);
		_tmp12_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp11_, gtk_box_get_type ()) ? ((GtkBox*) _tmp11_) : NULL);
		content = _tmp12_;
		_tmp13_ = content;
		_tmp14_ = ns_filetype;
		gtk_box_pack_start (_tmp13_, (GtkWidget*) _tmp14_, TRUE, TRUE, (guint) 10);
		_tmp15_ = dialog;
		gtk_container_set_border_width ((GtkContainer*) _tmp15_, (guint) 10);
		_tmp16_ = dialog;
		gtk_dialog_run (_tmp16_);
		_tmp17_ = dialog;
		gtk_widget_destroy ((GtkWidget*) _tmp17_);
		_g_object_unref0 (content);
		_g_object_unref0 (ns_filetype);
		_g_object_unref0 (dialog);
		return;
	}
	_tmp18_ = self->priv->tab_bar;
	gtk_widget_show ((GtkWidget*) _tmp18_);
	_tmp19_ = self->priv->separator;
	gtk_widget_show ((GtkWidget*) _tmp19_);
	_tmp20_ = self->priv->counter;
	self->priv->counter = _tmp20_ + 1;
	_tmp21_ = g_strdup_printf ("tab - %d", _tmp20_);
	tab_title = _tmp21_;
	_tmp22_ = file_name;
	_tmp23_ = g_path_get_basename (_tmp22_);
	_tmp24_ = _tmp23_;
	_tmp25_ = file_name;
	_tmp26_ = document_tab_new (_tmp24_, _tmp25_);
	g_object_ref_sink (_tmp26_);
	_tmp27_ = _tmp26_;
	_g_free0 (_tmp24_);
	tab = _tmp27_;
	_tmp28_ = self->priv->documents;
	_tmp29_ = tab;
	_tmp30_ = document_tab_get_tab_widget (_tmp29_);
	_tmp31_ = _tmp30_;
	_tmp32_ = tab_title;
	gtk_stack_add_named (_tmp28_, (GtkWidget*) _tmp31_, _tmp32_);
	_tmp33_ = self->priv->tab_bar;
	_tmp34_ = tab;
	tab_bar_add_page (_tmp33_, _tmp34_, TRUE);
	_tmp35_ = self->priv->tab_bar;
	_tmp36_ = self->priv->documents;
	_tmp37_ = gtk_stack_get_visible_child (_tmp36_);
	_tmp38_ = _tmp37_;
	_tmp39_ = tab_bar_get_current_page (_tmp35_, _tmp38_);
	current_page = _tmp39_;
	_tmp40_ = self->priv->tab_bar;
	_tmp41_ = current_page;
	_tmp42_ = tab_bar_get_page_num (_tmp40_, _tmp41_);
	page_num = _tmp42_;
	_tmp43_ = file_name;
	_tmp44_ = g_strdup (_tmp43_);
	_tmp45_ = page_num;
	self->priv->opened_files = g_list_insert (self->priv->opened_files, _tmp44_, _tmp45_);
	_g_object_unref0 (current_page);
	_g_object_unref0 (tab);
	_g_free0 (tab_title);
}


static gboolean main_window_file_is_opened (MainWindow* self, const gchar* needle) {
	gboolean result = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (needle != NULL, FALSE);
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp0_ = FALSE;
			_tmp0_ = TRUE;
			while (TRUE) {
				gint _tmp2_ = 0;
				GList* _tmp3_ = NULL;
				guint _tmp4_ = 0U;
				const gchar* _tmp5_ = NULL;
				GList* _tmp6_ = NULL;
				gint _tmp7_ = 0;
				gconstpointer _tmp8_ = NULL;
				if (!_tmp0_) {
					gint _tmp1_ = 0;
					_tmp1_ = i;
					i = _tmp1_ + 1;
				}
				_tmp0_ = FALSE;
				_tmp2_ = i;
				_tmp3_ = self->priv->opened_files;
				_tmp4_ = g_list_length (_tmp3_);
				if (!(((guint) _tmp2_) < _tmp4_)) {
					break;
				}
				_tmp5_ = needle;
				_tmp6_ = self->priv->opened_files;
				_tmp7_ = i;
				_tmp8_ = g_list_nth_data (_tmp6_, (guint) _tmp7_);
				if (g_strcmp0 (_tmp5_, (const gchar*) _tmp8_) == 0) {
					result = TRUE;
					return result;
				}
			}
		}
	}
	result = FALSE;
	return result;
}


static void main_window_on_page_close (MainWindow* self, DocumentTab* tab, gint page_num) {
	GList* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gconstpointer _tmp2_ = NULL;
	TabBar* _tmp3_ = NULL;
	DocumentTab* _tmp4_ = NULL;
	DocumentTab* _tmp5_ = NULL;
	GtkScrolledWindow* _tmp6_ = NULL;
	GtkScrolledWindow* _tmp7_ = NULL;
	DocumentTab* _tmp8_ = NULL;
	TabBar* _tmp9_ = NULL;
	gint _tmp10_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->opened_files;
	_tmp1_ = page_num;
	_tmp2_ = g_list_nth_data (_tmp0_, (guint) _tmp1_);
	self->priv->opened_files = g_list_remove (self->priv->opened_files, (const gchar*) _tmp2_);
	_tmp3_ = self->priv->tab_bar;
	_tmp4_ = tab;
	tab_bar_switch_page_next (_tmp3_, _tmp4_);
	_tmp5_ = tab;
	_tmp6_ = document_tab_get_tab_widget (_tmp5_);
	_tmp7_ = _tmp6_;
	gtk_widget_destroy ((GtkWidget*) _tmp7_);
	_tmp8_ = tab;
	gtk_widget_destroy ((GtkWidget*) _tmp8_);
	_tmp9_ = self->priv->tab_bar;
	_tmp10_ = _tmp9_->tab_num;
	if (_tmp10_ == 0) {
		GtkSeparator* _tmp11_ = NULL;
		_tmp11_ = self->priv->separator;
		gtk_widget_hide ((GtkWidget*) _tmp11_);
	} else {
		TabBar* _tmp12_ = NULL;
		GtkStack* _tmp13_ = NULL;
		GtkWidget* _tmp14_ = NULL;
		GtkWidget* _tmp15_ = NULL;
		DocumentTab* _tmp16_ = NULL;
		DocumentTab* _tmp17_ = NULL;
		_tmp12_ = self->priv->tab_bar;
		_tmp13_ = self->priv->documents;
		_tmp14_ = gtk_stack_get_visible_child (_tmp13_);
		_tmp15_ = _tmp14_;
		_tmp16_ = tab_bar_get_current_page (_tmp12_, _tmp15_);
		_tmp17_ = _tmp16_;
		document_tab_mark_title (_tmp17_);
		_g_object_unref0 (_tmp17_);
	}
}


static void main_window_page_refresh_cb (MainWindow* self) {
	DocumentTab* current_page = NULL;
	TabBar* _tmp0_ = NULL;
	GtkStack* _tmp1_ = NULL;
	GtkWidget* _tmp2_ = NULL;
	GtkWidget* _tmp3_ = NULL;
	DocumentTab* _tmp4_ = NULL;
	DocumentTab* _tmp5_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->tab_bar;
	_tmp1_ = self->priv->documents;
	_tmp2_ = gtk_stack_get_visible_child (_tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = tab_bar_get_current_page (_tmp0_, _tmp3_);
	current_page = _tmp4_;
	_tmp5_ = current_page;
	if (_tmp5_ != NULL) {
		DocumentTab* _tmp6_ = NULL;
		_tmp6_ = current_page;
		document_tab_load_file (_tmp6_);
	}
	_g_object_unref0 (current_page);
}


static void main_window_next_tab_cb (MainWindow* self) {
	DocumentTab* current_page = NULL;
	TabBar* _tmp0_ = NULL;
	GtkStack* _tmp1_ = NULL;
	GtkWidget* _tmp2_ = NULL;
	GtkWidget* _tmp3_ = NULL;
	DocumentTab* _tmp4_ = NULL;
	DocumentTab* _tmp5_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->tab_bar;
	_tmp1_ = self->priv->documents;
	_tmp2_ = gtk_stack_get_visible_child (_tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = tab_bar_get_current_page (_tmp0_, _tmp3_);
	current_page = _tmp4_;
	_tmp5_ = current_page;
	if (_tmp5_ != NULL) {
		TabBar* _tmp6_ = NULL;
		DocumentTab* _tmp7_ = NULL;
		_tmp6_ = self->priv->tab_bar;
		_tmp7_ = current_page;
		tab_bar_switch_page_next (_tmp6_, _tmp7_);
	}
	_g_object_unref0 (current_page);
}


static void main_window_prev_tab_cb (MainWindow* self) {
	DocumentTab* current_page = NULL;
	TabBar* _tmp0_ = NULL;
	GtkStack* _tmp1_ = NULL;
	GtkWidget* _tmp2_ = NULL;
	GtkWidget* _tmp3_ = NULL;
	DocumentTab* _tmp4_ = NULL;
	DocumentTab* _tmp5_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->tab_bar;
	_tmp1_ = self->priv->documents;
	_tmp2_ = gtk_stack_get_visible_child (_tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = tab_bar_get_current_page (_tmp0_, _tmp3_);
	current_page = _tmp4_;
	_tmp5_ = current_page;
	if (_tmp5_ != NULL) {
		TabBar* _tmp6_ = NULL;
		DocumentTab* _tmp7_ = NULL;
		_tmp6_ = self->priv->tab_bar;
		_tmp7_ = current_page;
		tab_bar_switch_page_prev (_tmp6_, _tmp7_);
	}
	_g_object_unref0 (current_page);
}


static GFile** _vala_array_dup1 (GFile** self, int length) {
	GFile** result;
	int i;
	result = g_new0 (GFile*, length + 1);
	for (i = 0; i < length; i++) {
		GFile* _tmp0_ = NULL;
		_tmp0_ = _g_object_ref0 (self[i]);
		result[i] = _tmp0_;
	}
	return result;
}


void main_window_set_arg_files (MainWindow* self, GFile** value, int value_length1) {
	GFile** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	GFile** _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	GFile** _tmp2_ = NULL;
	gint _tmp2__length1 = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp0__length1 = value_length1;
	_tmp1_ = (_tmp0_ != NULL) ? _vala_array_dup1 (_tmp0_, _tmp0__length1) : ((gpointer) _tmp0_);
	_tmp1__length1 = _tmp0__length1;
	self->priv->_arg_files = (_vala_array_free (self->priv->_arg_files, self->priv->_arg_files_length1, (GDestroyNotify) g_object_unref), NULL);
	self->priv->_arg_files = _tmp1_;
	self->priv->_arg_files_length1 = _tmp1__length1;
	self->priv->__arg_files_size_ = self->priv->_arg_files_length1;
	_tmp2_ = self->priv->_arg_files;
	_tmp2__length1 = self->priv->_arg_files_length1;
	if (_tmp2_ != NULL) {
		GFile** _tmp3_ = NULL;
		gint _tmp3__length1 = 0;
		_tmp3_ = self->priv->_arg_files;
		_tmp3__length1 = self->priv->_arg_files_length1;
		{
			GFile** file_collection = NULL;
			gint file_collection_length1 = 0;
			gint _file_collection_size_ = 0;
			gint file_it = 0;
			file_collection = _tmp3_;
			file_collection_length1 = _tmp3__length1;
			for (file_it = 0; file_it < _tmp3__length1; file_it = file_it + 1) {
				GFile* _tmp4_ = NULL;
				GFile* file = NULL;
				_tmp4_ = _g_object_ref0 (file_collection[file_it]);
				file = _tmp4_;
				{
					GFile* _tmp5_ = NULL;
					gchar* _tmp6_ = NULL;
					gchar* _tmp7_ = NULL;
					_tmp5_ = file;
					_tmp6_ = g_file_get_path (_tmp5_);
					_tmp7_ = _tmp6_;
					main_window_add_new_tab_from_file (self, _tmp7_);
					_g_free0 (_tmp7_);
					_g_object_unref0 (file);
				}
			}
		}
	}
}


static void main_window_class_init (MainWindowClass * klass) {
	main_window_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (MainWindowPrivate));
	G_OBJECT_CLASS (klass)->set_property = _vala_main_window_set_property;
	G_OBJECT_CLASS (klass)->finalize = main_window_finalize;
}


static void main_window_instance_init (MainWindow * self) {
	self->priv = MAIN_WINDOW_GET_PRIVATE (self);
	self->priv->counter = 0;
	self->priv->_arg_files = NULL;
	self->priv->_arg_files_length1 = 0;
	self->priv->__arg_files_size_ = self->priv->_arg_files_length1;
}


static void main_window_finalize (GObject* obj) {
	MainWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_MAIN_WINDOW, MainWindow);
	_g_object_unref0 (self->priv->headerbar);
	_g_object_unref0 (self->priv->tab_bar);
	_g_object_unref0 (self->priv->documents);
	_g_object_unref0 (self->priv->separator);
	__g_list_free__g_free0_0 (self->priv->opened_files);
	self->priv->_arg_files = (_vala_array_free (self->priv->_arg_files, self->priv->_arg_files_length1, (GDestroyNotify) g_object_unref), NULL);
	G_OBJECT_CLASS (main_window_parent_class)->finalize (obj);
}


GType main_window_get_type (void) {
	static volatile gsize main_window_type_id__volatile = 0;
	if (g_once_init_enter (&main_window_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MainWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) main_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MainWindow), 0, (GInstanceInitFunc) main_window_instance_init, NULL };
		GType main_window_type_id;
		main_window_type_id = g_type_register_static (gtk_application_window_get_type (), "MainWindow", &g_define_type_info, 0);
		g_once_init_leave (&main_window_type_id__volatile, main_window_type_id);
	}
	return main_window_type_id__volatile;
}


static void _vala_main_window_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	MainWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_MAIN_WINDOW, MainWindow);
	switch (property_id) {
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



