/* markdown-reader.c generated by valac 0.28.0, the Vala compiler
 * generated from markdown-reader.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>


#define TYPE_MARKDOWN_READER (markdown_reader_get_type ())
#define MARKDOWN_READER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MARKDOWN_READER, MarkdownReader))
#define MARKDOWN_READER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MARKDOWN_READER, MarkdownReaderClass))
#define IS_MARKDOWN_READER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MARKDOWN_READER))
#define IS_MARKDOWN_READER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MARKDOWN_READER))
#define MARKDOWN_READER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MARKDOWN_READER, MarkdownReaderClass))

typedef struct _MarkdownReader MarkdownReader;
typedef struct _MarkdownReaderClass MarkdownReaderClass;
typedef struct _MarkdownReaderPrivate MarkdownReaderPrivate;

#define TYPE_MAIN_WINDOW (main_window_get_type ())
#define MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAIN_WINDOW, MainWindow))
#define MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MAIN_WINDOW, MainWindowClass))
#define IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAIN_WINDOW))
#define IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MAIN_WINDOW))
#define MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MAIN_WINDOW, MainWindowClass))

typedef struct _MainWindow MainWindow;
typedef struct _MainWindowClass MainWindowClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _MarkdownReader {
	GtkApplication parent_instance;
	MarkdownReaderPrivate * priv;
};

struct _MarkdownReaderClass {
	GtkApplicationClass parent_class;
};

struct _MarkdownReaderPrivate {
	gchar* home_dir;
	MainWindow* window;
};


static gpointer markdown_reader_parent_class = NULL;

GType markdown_reader_get_type (void) G_GNUC_CONST;
GType main_window_get_type (void) G_GNUC_CONST;
#define MARKDOWN_READER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_MARKDOWN_READER, MarkdownReaderPrivate))
enum  {
	MARKDOWN_READER_DUMMY_PROPERTY
};
static void markdown_reader_about_cb (MarkdownReader* self);
static void _markdown_reader_about_cb_gsimple_action_activate_callback (GSimpleAction* action, GVariant* parameter, gpointer self);
static void markdown_reader_quit_cb (MarkdownReader* self);
static void _markdown_reader_quit_cb_gsimple_action_activate_callback (GSimpleAction* action, GVariant* parameter, gpointer self);
MarkdownReader* markdown_reader_new (void);
MarkdownReader* markdown_reader_construct (GType object_type);
static void markdown_reader_real_startup (GApplication* base);
MainWindow* main_window_new (GtkApplication* app);
MainWindow* main_window_construct (GType object_type, GtkApplication* app);
static void markdown_reader_real_activate (GApplication* base);
void main_window_set_arg_files (MainWindow* self, GFile** value, int value_length1);
static void markdown_reader_real_open (GApplication* base, GFile** files, int files_length1, const gchar* hint);
static void markdown_reader_real_shutdown (GApplication* base);
gint markdown_reader_main (gchar** args, int args_length1);
static void markdown_reader_finalize (GObject* obj);

static const GActionEntry MARKDOWN_READER_app_entries[2] = {{"about", _markdown_reader_about_cb_gsimple_action_activate_callback, NULL, NULL, NULL}, {"quit", _markdown_reader_quit_cb_gsimple_action_activate_callback, NULL, NULL, NULL}};

static void _markdown_reader_about_cb_gsimple_action_activate_callback (GSimpleAction* action, GVariant* parameter, gpointer self) {
	markdown_reader_about_cb ((MarkdownReader*) self);
}


static void _markdown_reader_quit_cb_gsimple_action_activate_callback (GSimpleAction* action, GVariant* parameter, gpointer self) {
	markdown_reader_quit_cb ((MarkdownReader*) self);
}


MarkdownReader* markdown_reader_construct (GType object_type) {
	MarkdownReader * self = NULL;
	self = (MarkdownReader*) g_object_new (object_type, "application-id", "badwolfie.markdown-reader.app", "flags", G_APPLICATION_HANDLES_OPEN, NULL);
	return self;
}


MarkdownReader* markdown_reader_new (void) {
	return markdown_reader_construct (TYPE_MARKDOWN_READER);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void markdown_reader_real_startup (GApplication* base) {
	MarkdownReader * self;
	GFile* conf_dir = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	GFile* _tmp3_ = NULL;
	GFile* _tmp4_ = NULL;
	GFile* tmp_dir = NULL;
	const gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	GFile* _tmp8_ = NULL;
	GFile* _tmp9_ = NULL;
	MainWindow* _tmp17_ = NULL;
	GtkBuilder* builder = NULL;
	GtkBuilder* _tmp18_ = NULL;
	GMenuModel* menu = NULL;
	GObject* _tmp20_ = NULL;
	GMenuModel* _tmp21_ = NULL;
	GError * _inner_error_ = NULL;
	self = (MarkdownReader*) base;
	G_APPLICATION_CLASS (markdown_reader_parent_class)->startup ((GApplication*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_application_get_type (), GtkApplication));
	_tmp0_ = self->priv->home_dir;
	_tmp1_ = g_strconcat (_tmp0_, "/.markdown-reader", NULL);
	_tmp2_ = _tmp1_;
	_tmp3_ = g_file_new_for_path (_tmp2_);
	_tmp4_ = _tmp3_;
	_g_free0 (_tmp2_);
	conf_dir = _tmp4_;
	_tmp5_ = self->priv->home_dir;
	_tmp6_ = g_strconcat (_tmp5_, "/.markdown-reader/tmp", NULL);
	_tmp7_ = _tmp6_;
	_tmp8_ = g_file_new_for_path (_tmp7_);
	_tmp9_ = _tmp8_;
	_g_free0 (_tmp7_);
	tmp_dir = _tmp9_;
	{
		GFile* _tmp10_ = NULL;
		gboolean _tmp11_ = FALSE;
		GFile* _tmp13_ = NULL;
		gboolean _tmp14_ = FALSE;
		_tmp10_ = conf_dir;
		_tmp11_ = g_file_query_exists (_tmp10_, NULL);
		if (!_tmp11_) {
			GFile* _tmp12_ = NULL;
			_tmp12_ = conf_dir;
			g_file_make_directory (_tmp12_, NULL, &_inner_error_);
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				goto __catch0_g_error;
			}
		}
		_tmp13_ = tmp_dir;
		_tmp14_ = g_file_query_exists (_tmp13_, NULL);
		if (!_tmp14_) {
			GFile* _tmp15_ = NULL;
			_tmp15_ = tmp_dir;
			g_file_make_directory (_tmp15_, NULL, &_inner_error_);
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				goto __catch0_g_error;
			}
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		const gchar* _tmp16_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp16_ = e->message;
		g_error ("markdown-reader.vala:29: Error loading menu UI: %s", _tmp16_);
		_g_error_free0 (e);
	}
	__finally0:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (tmp_dir);
		_g_object_unref0 (conf_dir);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	g_action_map_add_action_entries ((GActionMap*) self, MARKDOWN_READER_app_entries, G_N_ELEMENTS (MARKDOWN_READER_app_entries), self);
	_tmp17_ = main_window_new ((GtkApplication*) self);
	g_object_ref_sink (_tmp17_);
	_g_object_unref0 (self->priv->window);
	self->priv->window = _tmp17_;
	_tmp18_ = gtk_builder_new ();
	builder = _tmp18_;
	{
		gtk_builder_add_from_resource (builder, "/com/github/badwolfie/markdown-reader/menu.ui", &_inner_error_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch1_g_error;
		}
	}
	goto __finally1;
	__catch1_g_error:
	{
		GError* e = NULL;
		const gchar* _tmp19_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp19_ = e->message;
		g_error ("markdown-reader.vala:40: Error loading menu UI: %s", _tmp19_);
		_g_error_free0 (e);
	}
	__finally1:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (builder);
		_g_object_unref0 (tmp_dir);
		_g_object_unref0 (conf_dir);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp20_ = gtk_builder_get_object (builder, "appmenu");
	_tmp21_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp20_, g_menu_model_get_type ()) ? ((GMenuModel*) _tmp20_) : NULL);
	menu = _tmp21_;
	gtk_application_set_app_menu ((GtkApplication*) self, menu);
	_g_object_unref0 (menu);
	_g_object_unref0 (builder);
	_g_object_unref0 (tmp_dir);
	_g_object_unref0 (conf_dir);
}


static void markdown_reader_real_activate (GApplication* base) {
	MarkdownReader * self;
	MainWindow* _tmp0_ = NULL;
	MainWindow* _tmp1_ = NULL;
	self = (MarkdownReader*) base;
	G_APPLICATION_CLASS (markdown_reader_parent_class)->activate ((GApplication*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_application_get_type (), GtkApplication));
	_tmp0_ = self->priv->window;
	main_window_set_arg_files (_tmp0_, NULL, 0);
	_tmp1_ = self->priv->window;
	gtk_window_present ((GtkWindow*) _tmp1_);
}


static void markdown_reader_real_open (GApplication* base, GFile** files, int files_length1, const gchar* hint) {
	MarkdownReader * self;
	GFile** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	const gchar* _tmp1_ = NULL;
	MainWindow* _tmp2_ = NULL;
	GFile** _tmp3_ = NULL;
	gint _tmp3__length1 = 0;
	MainWindow* _tmp4_ = NULL;
	self = (MarkdownReader*) base;
	g_return_if_fail (hint != NULL);
	_tmp0_ = files;
	_tmp0__length1 = files_length1;
	_tmp1_ = hint;
	G_APPLICATION_CLASS (markdown_reader_parent_class)->open ((GApplication*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_application_get_type (), GtkApplication), _tmp0_, _tmp0__length1, _tmp1_);
	_tmp2_ = self->priv->window;
	_tmp3_ = files;
	_tmp3__length1 = files_length1;
	main_window_set_arg_files (_tmp2_, _tmp3_, _tmp3__length1);
	_tmp4_ = self->priv->window;
	gtk_window_present ((GtkWindow*) _tmp4_);
}


static void markdown_reader_real_shutdown (GApplication* base) {
	MarkdownReader * self;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	self = (MarkdownReader*) base;
	G_APPLICATION_CLASS (markdown_reader_parent_class)->shutdown ((GApplication*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_application_get_type (), GtkApplication));
	_tmp0_ = self->priv->home_dir;
	_tmp1_ = g_strconcat ("rm -f ", _tmp0_, NULL);
	_tmp2_ = _tmp1_;
	_tmp3_ = g_strconcat (_tmp2_, "/.markdown-reader/tmp/*", NULL);
	_tmp4_ = _tmp3_;
	system (_tmp4_);
	_g_free0 (_tmp4_);
	_g_free0 (_tmp2_);
}


static void markdown_reader_about_cb (MarkdownReader* self) {
	static const gchar* authors[] = {"Ian Hernández <ihernandezs@openmailbox.org>"};
	gchar* license = NULL;
	gchar* _tmp0_ = NULL;
	GtkAboutDialog* about_dialog = NULL;
	GtkAboutDialog* _tmp1_ = NULL;
	MainWindow* _tmp2_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup ("Markdown Reader is free software: you can redistribute it and/or modif" \
"y\n" \
"it under the terms of the GNU General Public License as published by\n" \
"the Free Software Foundation, either version 2 of the License, or\n" \
"(at your option) any later version.\n" \
"\n" \
"Markdown Reader is distributed in the hope that it will be useful,\n" \
"but WITHOUT ANY WARRANTY; without even the implied warranty of\n" \
"MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the\n" \
"GNU General Public License for more details.\n" \
"\n" \
"You should have received a copy of the GNU General Public License\n" \
"along with Markdown Reader. If not, see <http://www.gnu.org/licenses/>" \
".");
	license = _tmp0_;
	_tmp1_ = (GtkAboutDialog*) gtk_about_dialog_new ();
	g_object_ref_sink (_tmp1_);
	about_dialog = _tmp1_;
	_tmp2_ = self->priv->window;
	gtk_window_set_transient_for ((GtkWindow*) about_dialog, (GtkWindow*) _tmp2_);
	gtk_about_dialog_set_program_name (about_dialog, "Markdown Reader");
	gtk_window_set_title ((GtkWindow*) about_dialog, "About" " Markdown Reader");
	gtk_about_dialog_set_copyright (about_dialog, "Copyright \xc2\xa9 2015 Ian Hernández");
	gtk_about_dialog_set_comments (about_dialog, "A document reader for markdown and html files");
	gtk_about_dialog_set_website (about_dialog, "https://github.com/BadWolfie/markdown-reader");
	gtk_about_dialog_set_website_label (about_dialog, "Web page");
	gtk_about_dialog_set_license (about_dialog, license);
	gtk_about_dialog_set_logo_icon_name (about_dialog, "gnome-documents");
	gtk_about_dialog_set_documenters (about_dialog, authors);
	gtk_about_dialog_set_authors (about_dialog, authors);
	gtk_about_dialog_set_version (about_dialog, "1.0.0");
	gtk_dialog_run ((GtkDialog*) about_dialog);
	gtk_widget_destroy ((GtkWidget*) about_dialog);
	_g_object_unref0 (about_dialog);
	_g_free0 (license);
}


static void markdown_reader_quit_cb (MarkdownReader* self) {
	MainWindow* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->window;
	gtk_widget_destroy ((GtkWidget*) _tmp0_);
}


gint markdown_reader_main (gchar** args, int args_length1) {
	gint result = 0;
	MarkdownReader* app = NULL;
	MarkdownReader* _tmp0_ = NULL;
	gchar** _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	gint _tmp2_ = 0;
	gtk_window_set_default_icon_name ("gnome-documents");
	_tmp0_ = markdown_reader_new ();
	app = _tmp0_;
	_tmp1_ = args;
	_tmp1__length1 = args_length1;
	_tmp2_ = g_application_run ((GApplication*) app, _tmp1__length1, _tmp1_);
	result = _tmp2_;
	_g_object_unref0 (app);
	return result;
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	return markdown_reader_main (argv, argc);
}


static void markdown_reader_class_init (MarkdownReaderClass * klass) {
	markdown_reader_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (MarkdownReaderPrivate));
	((GApplicationClass *) klass)->startup = markdown_reader_real_startup;
	((GApplicationClass *) klass)->activate = markdown_reader_real_activate;
	((GApplicationClass *) klass)->open = markdown_reader_real_open;
	((GApplicationClass *) klass)->shutdown = markdown_reader_real_shutdown;
	G_OBJECT_CLASS (klass)->finalize = markdown_reader_finalize;
}


static void markdown_reader_instance_init (MarkdownReader * self) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	self->priv = MARKDOWN_READER_GET_PRIVATE (self);
	_tmp0_ = g_get_home_dir ();
	_tmp1_ = g_strdup (_tmp0_);
	self->priv->home_dir = _tmp1_;
}


static void markdown_reader_finalize (GObject* obj) {
	MarkdownReader * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_MARKDOWN_READER, MarkdownReader);
	_g_free0 (self->priv->home_dir);
	_g_object_unref0 (self->priv->window);
	G_OBJECT_CLASS (markdown_reader_parent_class)->finalize (obj);
}


GType markdown_reader_get_type (void) {
	static volatile gsize markdown_reader_type_id__volatile = 0;
	if (g_once_init_enter (&markdown_reader_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MarkdownReaderClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) markdown_reader_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MarkdownReader), 0, (GInstanceInitFunc) markdown_reader_instance_init, NULL };
		GType markdown_reader_type_id;
		markdown_reader_type_id = g_type_register_static (gtk_application_get_type (), "MarkdownReader", &g_define_type_info, 0);
		g_once_init_leave (&markdown_reader_type_id__volatile, markdown_reader_type_id);
	}
	return markdown_reader_type_id__volatile;
}



